# Generated by Django 2.2.4 on 2019-08-15 00:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('slug', models.SlugField(max_length=30, verbose_name='Nome Fantasia')),
                ('age', models.PositiveIntegerField(verbose_name='Idade')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
                ('profile_picture', models.ImageField(upload_to=core.models.upload_image_path, verbose_name='Foto do Perfil')),
                ('cacheForHours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cachê/Hr')),
                ('weight', models.FloatField(verbose_name='Peso(kg)')),
                ('height', models.FloatField(verbose_name='Altura(m)')),
                ('bust', models.FloatField(verbose_name='Busto(cm)')),
                ('waist', models.FloatField(verbose_name='Cintura(cm)')),
                ('butt', models.FloatField(verbose_name='Bunda(cm)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em ')),
            ],
        ),
    ]
