# Generated by Django 2.2.4 on 2019-08-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
